name: CICD WORKFLOW

on:
 push:
  branches:
   - devel

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: cd codebase/rdicidr-0.1.0 && npm install
      - run: cd codebase/rdicidr-0.1.0 && npm run lint
      - run: cd codebase/rdicidr-0.1.0 && npm run prettier
      - run: cd codebase/rdicidr-0.1.0 && npm run test
      - run: cd codebase/rdicidr-0.1.0 && npm run build --if-present
      - uses: actions/upload-artifact@v3
        with:
         name: my-artifact
         path: codebase/rdicidr-0.1.0/build
