name: Node.js CI for Custom Path

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up the correct version of Node.js and npm
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'  # Set the correct Node.js version (>= 15.0.0 < 16.0.0)
        check-latest: true

    # Upgrade npm to the required version
    - name: Upgrade npm to 7.x
      run: npm install -g npm@7

    # Cache Node.js modules with the correct path to package-lock.json
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: codebase/rdicidr-0.1.0/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('codebase/rdicidr-0.1.0/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Install dependencies from the codebase/rdicidr-0.1.0 directory
    - name: Install dependencies
      run: |
        cd codebase/rdicidr-0.1.0
        npm install

    # Run linter (ESLint) from the correct directory
    - name: Run linter (ESLint)
      run: |
        cd codebase/rdicidr-0.1.0
        npm run lint

    # Run formatter (Prettier) from the correct directory
    - name: Run formatter (Prettier)
      run: |
        cd codebase/rdicidr-0.1.0
        npm run prettier

    # Run tests (Jest) from the correct directory
    - name: Run tests (Jest)
      env:
        CI: true
      run: |
        cd codebase/rdicidr-0.1.0
        npm run test

    # Build the project from the correct directory
    - name: Build the project
      run: |
        cd codebase/rdicidr-0.1.0
        npm run build
